import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    padding: 16,
  },
  header: {
    marginTop: 10,
    backgroundColor: "white",
    borderRadius: 20,
    alignSelf: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 2,
  },
  headerText: {
    fontSize: 32,
    textAlign: "center",
    fontFamily: "coolveticarg",
    textTransform: "uppercase",
  },
  buttonContainer: {
    marginVertical: 10,
    alignSelf: "center",
    width: "50%",
    flexDirection: "row",
    marginTop: 10,
    justifyContent: "space-between",
    alignItems: "center",
  },
  itemList: {
    backgroundColor: "white",
    justifyContent: "center",
    borderRadius: 20,
    width: "80%",
    alignSelf: "center",
    marginTop: 10,
  },
  listItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    borderBottomWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "white",
  },
  itemContent: {
    flex: 1,
    marginRight: 10,
    backgroundColor: "white",
  },
  itemActions: {
    flexDirection: "row",
  },
  actionText: {
    color: "gray",
    marginHorizontal: 5,
  },
  addButton: {
    padding: 5,
    backgroundColor: "#ccc",
    borderRadius: 20,
    alignSelf: "flex-end",
    margin: 5,
    width: 80,
    marginRight: 10,
  },
  addButtonText: {
    fontSize: 16,
    fontFamily: "LouisGeorgeCafe",
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: "#fff",
    marginHorizontal: 30,
    padding: 20,
    borderRadius: 10,
    height: 250,
    justifyContent: "space-between",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "LouisGeorgeCafe",
    textTransform: "uppercase",
  },
  input: {
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    padding: 8,
    marginVertical: 10,
  },
  profileIcon: {
    height: 50,
    width: 50,
    borderWidth: 2,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginLeft: 20,
    marginRight: 20,
    marginTop: 5,
    marginBottom: 5,
  },
  addButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  button: {
    padding: 10,
    marginHorizontal: 5,
    alignItems: "center",
    borderRadius: 20,
  },
  successButton: {
    backgroundColor: "#B3C17A",
    borderColor: "#98A869",
    borderWidth: 2,
    marginHorizontal: 5,
    padding: 10,
  },
  cancelButton: {
    backgroundColor: "#ff8c8c",
    borderColor: "#ff5c5c",
    borderWidth: 2,
    marginHorizontal: 5,
    padding: 10,
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "LouisGeorgeCafe",
    textTransform: "uppercase",
  },
  background: {
    backgroundColor: "#E7C6CD",
    flex: 1,
    justifyContent: "center",
    padding: 0,
    width: "100%",
  },
  greenPageSection: {
    backgroundColor: "#98A869",
    width: "100%",
    paddingTop: 30,
    paddingBottom: 10,
    flex: 1,
  },
  pageContentContainer: {
    borderRadius: 20,
    padding: 10,
    backgroundColor: "white",
    width: "80%",
    height: "80%",
    alignSelf: "center",
    marginBottom: 5,
  },
  welcomeButton: {
    alignItems: "center",
    backgroundColor: "#98A869",
    padding: 5,
    width: "60%",
    alignSelf: "center",
    marginBottom: 5,
    borderRadius: 20,
  },
  welcomeBackground: {
    backgroundColor: "#E7C6CD",
    flex: 1,
    justifyContent: "center",
  },
  welcomeButtonText: {
    fontFamily: "LouisGeorgeCafe",
    fontSize: 18,
    fontWeight: "bold",
  },
  welcomefont: {
    fontFamily: "LouisGeorgeCafe",
    fontSize: 20,
    textAlign: "center",
    marginBottom: 5,
  },
  profileHeader: {
    height: 200,
    width: 200,
    borderWidth: 2,
    borderRadius: 20,
    alignSelf: "center",
    margin: 20,
  },
  budgetItem: {
    fontSize: 16,
    fontFamily: "coolveticarg",
    textTransform: "uppercase",
    width: "30%",
  },
  value: {
    fontSize: 16,
    fontFamily: "coolveticarg",
    textAlign: "left",
    width: "30%",
  },
  budgetCategories: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  progressBarContainer: {
    height: 30,
    width: 300,
    backgroundColor: "#e0e0df",
    borderRadius: 15,
    overflow: "hidden",
    marginVertical: 5,
    alignSelf: "center",
    marginTop: 60,
    borderWidth: 3,
    borderColor: "#98A869",
  },
  itemHeader: {
    fontSize: 10,
    fontFamily: "coolveticarg",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    paddingHorizontal: 10,
  },
  headerBudgetText: {
    flex: 1,
    textAlign: "left",
    fontWeight: "bold",
    color: "#333",
  },
  amount: {
    fontSize: 16,
    fontFamily: "coolveticarg",
    textAlign: "left",
    width: "30%",
  },
  total: {
    fontSize: 60,
    color: "#0",
  },
  ProgressText: {
    fontFamily: "coolveticarg",
    textAlign: "center",
  },
  savings: {
    color: "#656038",
    fontSize: 25,
  },
});
